server:
  port: 8084

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://config:config_pass@localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/finpay_notifications
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:test@gmail.com}
    password: ${MAIL_PASSWORD:testpass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka_pass@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
